[
  {
    "type": "dcdc",
    "model": "RBC50D1S-G1",
    "device_id": 96,
    "battery_percentage": 100,
    "battery_voltage": 14.1,
    "battery_current": 49.24,
    "battery_temperature": 25,
    "controller_temperature": 27,
    "charging_status": "current limiting",
    "load_status": "off",
    "load_voltage": 13.9,
    "load_current": 49.64,
    "load_power": 690,
    "pv_voltage": 0.0,
    "pv_current": 0.0,
    "pv_power": 694,
    "max_charging_power_today": 693,
    "max_discharging_power_today": 0,
    "charging_amp_hours_today": 14,
    "discharging_amp_hours_today": 0,
    "power_generation_today": 193,
    "power_consumption_today": 0,
    "power_generation_total": 60066,
    "battery_type": "lithium"
  },
  {
    "type": "battery",
    "cell_count": 4,
    "cell_voltage_0": 3.3,
    "cell_voltage_1": 3.3,
    "cell_voltage_2": 3.3,
    "cell_voltage_3": 3.3,
    "min_cell_voltage": 3.3,
    "max_cell_voltage": 3.3,
    "avg_cell_voltage": 3.3,
    "cell_voltage_diff": 0.0,
    "sensor_count": 4,
    "temperature_0": 21.0,
    "temperature_1": 22.0,
    "temperature_2": 22.0,
    "temperature_3": 21.0,
    "min_temperature": 21.0,
    "max_temperature": 22.0,
    "avg_temperature": 21.5,
    "current": 45.85,
    "voltage": 13.6,
    "remaining_charge": 92.47,
    "capacity": 99.99,
    "soc_percent": 92.5,
    "power": 623.56,
    "status": "charging",
    "model": "RBT100LFP12S-G1",
    "device_id": 48
  }
]